spring:

  # JPA
  jpa:
    hibernate:
      ddl-auto: none
# Log
logging:
  level:
    root: info
    org.springframework.security: debug


# P6spy
decorator:
  datasource:
    p6spy:
      enable-logging: true