# P6spy
decorator:
  datasource:
    p6spy:
      enable-logging: true

# Logging
logging:
  level:
    org.springframework.security: debug

# Monitoring
management:
  endpoints:
    web:
      exposure:
        include: beans
